browser=chrome
url=https://automationexercise.com/

InvalidEmail=jig@yopmail.com
InvalidPassword=Jivi123

CartPageEmail=jivi@yopmail.com
CartPagePassword=Jivi@1122

CheckoutPageEmail=jiv@yopmail.com
CheckoutPagePassword=Jivi@1122

PaymentPageEmail=jig@yopmail.com
PaymentPagePassword=Jivi@1122